version: "3"

services: 
  jupyter_lab:
    container_name: jupyter_lab
    build: .
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
    volumes:
      - ./work:/home/jovyan/work